---
name: Unittest
run-name: unit tests
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 -m pip install Pillow
      - run: python3 file_renamer/test/file_renamer_unittest.py
  gui-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: apt update
      - run: apt install -y python3-tk
      - run: python3 -m pip install Pillow
      - run: python3 -m pip install robotframework      
      - run: robot file_renamer/test/file_renamer_gui_test.robot
      - uses: actions/upload-artifact@v4
        with:
          path: |
            report.html
            log.html
...
